services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        environment:
            - SESSION_DRIVER=file
            - CACHE_DRIVER=file
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        ports:
            - "8083:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge